### PR TITLE
maintenance: change ^ to ~ in packages

### PR DESCRIPTION
**Pull request by kmdrGroch**
Partially solves #1589.
Still not updated packages:
stryker\packages\core\package.json - @stryker-mutator/api
stryker\e2e\package.json - @types/semver, semver, ts-node, typescript, webpack
stryker\package.json - @types/mocha, @types/sinon, execa, tslint, typescript
(i still might be missing some)

Important to change:
stryker\packages\core\package.json - @stryker-mutator/api
stryker\package.json - @types/mocha, @types/sinon
But it will cause a lot of issues (It might be a PR more than 1 person should work)

less important but still: tslint, typescript
will cause more issues :/

Note:
Stryker supports node >= 8.
But we are using types for node 10.x.x
should we change it to 8.x.x for now, until support for 8 is dropped?

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@nicojs little guy is waiting for approval :x

**Comment by Archcry** [comment]
We just merged some dependabot stuff, could you update the pull-request :see_no_evil:

**Comment by kmdrGroch** [comment]
@nicojs, @simondel, @Archcry  could we please wait with updating dependencies until we fix this issue? :)

**Comment by nicojs** [comment]
> Stryker supports node >= 8.
> But we are using types for node 10.x.x
> should we change it to 8.x.x for now, until support for 8 is dropped?

No, we shouldn't change it to 8.x.x. We did this practice in the past, however as the typings for 8.x.x are effectively frozen we don't get all the awesome typing improvements the good guys over at definitely typed provide. That's why we use the latest typings and run indeed the risk of using something that we shouldn't. We trust our tests enough.

Will merge after conflicts are solved

**Pull request closed without merging**
