### PR TITLE
Javascript - Ignore configured expressions

### PR DESCRIPTION
**Pull request by itsmeraji**
Please check this PR. This is an attempt to configure the statements to be removed from getting mutated.

### CODE REVIEW

**Comment by itsmeraji** [comment]
@nicojs / @kmdrGroch , we've been waiting for ignoring propTypes and such from mutation in Stryker. This PR has the relevant changes. Please check and let me know if this will hold good.

**Comment by simondel** [comment]
We want to introduce a parser API to support an easy and safe way to make the exclusions. This issue will lay the groundwork for it: #1893. Before this is done, we will not support this option.

We will keep your work here in mind as a reference ♥

**Comment by itsmeraji** [comment]
@simondel, Thanks for the response. When can we expect that useful parser API ? Our team wants to implement mutation testing but we re waiting for this for a long time.

**Comment by simondel** [comment]
We'll be working on this or the coming months. What's keeping you from using mutation testing without ignoring statements? It will result in a lower score, but that will simply be your baseline.

**Comment by itsmeraji** [comment]
We have a lot of applications and the developers feel that their testing score is less because there are a lot of things that shouldn't be really tested (like propTypes, PropTypes.oneof, logger.debug, etc), but mutation is done for everything. So we wanted to ignore the unwanted mutations before widely practicing it.

**Pull request closed without merging**
