### PR TITLE
feat: solve #1076 , #436

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Note: there is no deprecation warning.
Note: there are still places where ``projectType`` is said to be ``default`` not ``custom``

**Comment by simondel** [comment]
Hi @kmdrGroch Could you create a separate PR for #1076? That makes it easier to review since there are 3.000 changed lines in this pull request.

This also makes it easier for us to release the pull request since our changelog and version change is based on the commit messages. So if I would merge this one pull request, then every package would go a minor version up and every package will have a changelog entry saying the `project` property has been renamed.

**Comment by kmdrGroch** [comment]
@simondel I'll be able to do it tonight. If it is possible could you first merge this big change? It is mostly style changing then we will be able to work on #1076 easily

**Comment by simondel** [comment]
@kmdrGroch I think it will take me about one week to review the big change.

**Pull request closed without merging**
