### PR TITLE
fix mutation of Array constructor call for TypeScript

### LINKED ISSUE #1902: Mutator of Array constructor without `new` missing for TypeScript
**Summary**

The following test updates show Array constructor mutator that is missing for TypeScript:

```diff
--- a/packages/mutator-specification/src/ArrayDeclarationMutatorSpec.ts
+++ b/packages/mutator-specification/src/ArrayDeclarationMutatorSpec.ts
@@ -20,6 +20,9 @@ export default function ArrayDeclarationMutatorSpec(name: string, expectMutation
     it('should mutate filled Array constructor calls as empty arrays', () => {
       expectMutation('new Array(a, 1 + 1)', 'new Array()');
       expectMutation("new Array('val')", 'new Array()');
+      // XXX known issue on TypeScript mutator:
+      expectMutation("Array('val')", 'Array()');
+      expectMutation('Array(a, 1 + 1)', 'Array()');
     });
 
     it('should not mutate other new expressions', () => {
@@ -29,6 +32,8 @@ export default function ArrayDeclarationMutatorSpec(name: string, expectMutation
 
     it('should mutate empty array constructor call as a filled array', () => {
       expectMutation('new Array()', 'new Array([])');
+      // XXX known issue on TypeScript mutator:
+      expectMutation('Array()', 'Array([])');
     });
   });
 }

```

**Stryker config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/stryker.conf.js>

**Test runner config**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Stryker environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Test runner environment**

see <https://github.com/stryker-mutator/stryker/blob/master/packages/javascript-mutator/package.json>

**Your Environment**

| software         | version(s)
| ---------------- | -------
| node             | 12.13.1 |
| npm              | 6.12.1 |
| Operating System | Linux, macOS|

~~**Add stryker.log**~~

### PR DESCRIPTION
**Pull request by brodybits**
with testing

resolves #1902

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Looks good at first glance, but I think there might be a small mistake or a way to make this code shorter:
```js
} else if (node.kind === ts.SyntaxKind.CallExpression) {
      if (node.expression.kind === ts.SyntaxKind.Identifier && node.expression.getFullText(sourceFile).trim() === 'Array') {
        if (node.arguments && node.arguments.length) {
          return [{ node, replacement: 'Array()' }];
        } else {
          return [{ node, replacement: 'Array([])' }];
        }
      } else {
        return [];
      }
    } else {
      if (node.expression.getFullText(sourceFile).trim() === 'Array') {
        if (node.arguments && node.arguments.length) {
          return [{ node, replacement: 'new Array()' }];
        } else {
          return [{ node, replacement: 'new Array([])' }];
        }
      } else {
        return [];
      }
    }
```
This part looks fishy / strange. Especially that you are calling `node.expression.getFullText(sourceFile).trim() === 'Array'` in two places

**Comment by brodybits** [comment]
I pushed some changes to make the code shorter, and add another test case to hopefully ensure we do not make another mistake. I hope this is good to go soon, it is now blocking updates needed on PR #1898.

**Comment by kmdrGroch** [comment]
Now it looks much cleaner :D

**Comment by kmdrGroch** [comment]
@nicojs or @simondel if you could take a look / merge it :)

**Pull request merged**
