### PR TITLE
build(compile): Enable TS project references

### LINKED ISSUE #1301: reduce `npm test` time
We can shrink testing time by reducing `tslinting`
I noticed we are doing sth like:
- lint
- build
- lint
- build
....
- unit tests
- integration tests

We could do:
- lint all / throw error if exist /
- build
- tests

It will reduce development time, since sometimes there is small linting issue in last package, but you have to wait until everything before it is built

### PR DESCRIPTION
**Pull request by nicojs**
An improvement to our build system, using TS 3's project references. It supports awesome features:

Fixes #1290.
Fixes #1301 

* Build time improvement by more than 2 minutes!!
* One build process `tsc -b` (from the root directory).
* Watch all packages at once for changes, also supports build errors in other packages than the one you are changing: `npm start` or `npx tsc -b -w`
* We now have different configuration for test vs production code. So no more incidentally using `it` or `describe` in production code!!

~I've left the package specific vscode build configuration in tact for now. When we have more experience with this, I want to remove those as well.~ I've decided to remove the old "tasks.json" files. We can always recuperate them when we need them. I think this new way of working is pretty solid and don't want to keep files around that we don't want to maintain/use.

New way of working is explained in the CONTRIBUTING.md, but in general, everything works the same, but simpler 👍 . CTRL+SHIFT+B now directly triggers the compiler.

### CODE REVIEW

**Comment by kmdrGroch** [comment]
I guess it will fix the issue while testing `typescript` project with `coverageAnalysis: perTest`?

**Comment by nicojs** [comment]
Sorry, don't know what you're referring to. I don't think this fixes anything, but it doesn't break it either

**Comment by kmdrGroch** [comment]
> Sorry, don't know what you're referring to. I don't think this fixes anything, but it doesn't break it either

if you use config like this:
```js
module.exports = function(config) {
  config.set({
    mutator: "typescript",
    packageManager: "npm",
    reporters: ["html", "clear-text", "progress"],
    testRunner: "mocha",
    transpilers: ["typescript"],
    testFramework: "mocha",
    coverageAnalysis: "perTest",
    tsconfigFile: "tsconfig.json",
    mutate: ["src/**/*.ts"]
  });
};
```
You get error about `.d.ts` files. (But I see I didn't get this error right now... Well. Sometimes you can get it)

**Comment by nicojs** [comment]
Hmm interesting issue. Could you create a separate issue for that?

This PR doesn't change how the TypeScript transpiler or the TypeScript mutator plugins work. This is purely a technical PR that allows all our code to be transpiled with one TypeScript command, instead of running the `tsc` in each package. This dramatically improves performance of our builds as well as prevents us from using `describe` and `it` in production code.

**Comment by nicojs** [comment]
@kmdrGroch if you want, you may review this one

**Comment by kmdrGroch** [comment]
Looks good at the first glance. And Travis build looks really great

**Comment by kmdrGroch** [comment]
But if you can, please change `.gitignore`
```
.tscache
.stryker-tmp
*.js.map
-integrationTest/module/*.js
-integrationTest/module/*.map
-integrationTest/module/*.d.ts
-integrationTest/*.js
-integrationTest/*.map
-integrationTest/*.d.ts
+e2e/module/*.js
+e2e/module/*.map
+e2e/module/*.d.ts
+e2e/*.js
+e2e/*.map
+e2e/*.d.ts
packages/*/src/**/*.js
packages/*/test/**/*.js
packages/*/src/**/*.d.ts
```

**Comment by nicojs** [comment]
> I dunno if it was coincidence but it reduced build time for about 1.5minutes

Probably has to do with this:

> Build time improvement by more than 2 minutes!!

🏗 

I'll merge when the build is green. Thanks.

**Pull request merged**
