### PR TITLE
chore: add LICENSE file

### PR DESCRIPTION
**Pull request by philippw**

### CODE REVIEW

**Comment by nicojs** [comment]
@philippw thanks for your PR! Could you please change the commit message to `chore: add license file` as can be read in our contributors file? Thank you!

**Comment by simondel** [comment]
We could also do this by doing a squash merge I believe

**Comment by nicojs** [comment]
True 👍

**Comment by nicojs** [comment]
@philippw if you want you can also contribute to our [other repositories](https://github.com/stryker-mutator) :)

**Pull request merged**
