### PR TITLE
maintenance(eslint): kebab-case file names 

### PR DESCRIPTION
**Pull request by kmdrGroch**
fixes: #2338
Recommended: clone stryker again - especially on windows, some files might be broken after fetching (or use `git -rm --cached -r ./packages`, `git add .`)

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Finally @nicojs :)
Small breaking changes:
- entry point in `core` is `stryker` now not `Stryker`. 
- entry point for cli is `stryker-cli` not `StrykerCli`
- entry points (like core.ts, plugin.ts), might have a little bit different name (like going from Plugin to plugin)

**Comment by nicojs** [comment]
>  Small breaking changes:

I don't think changing private entry points is "breaking". We've never "officially" told people to import `import StrykerCli from '@stryker-mutator/core/src/StrykerCli`. Same goes for Stryker. We might want to add `StrykerCli` and `Stryker` in an `index.ts` and refer that in the `main` of the package.json. After that it is public and we should never change that.

**Review by nicojs — APPROVED** [review]
I think this is fine. How did you change the file names? By hand or with a

**Comment by kmdrGroch** [comment]
By hand :) linter only told which files, and then everything by hand. Imports errors too :)
So there is a small chance I misspelled something but we will find it sooner than later

**Comment by nicojs** [comment]
YOLO

**Pull request merged**
