### PR TITLE
feat(html-report): Revamp html report

### LINKED ISSUE #383: HTML report: Add back/home button
Right now, there is no way to move up one folder or go to the index page of a HTML report. Adding this would make it easier to navigate the report.

### LINKED ISSUE #385: HTML Report: Allow user to filter different mutant states
It would be useful if a user could differentiate between the different mutant states:

* Killed (green)
* Survived / NoCoverage (red)
* Timeout (yellow)
* TranspileError / RuntimeError (gray)

I think by default only timeout and survived mutants should be shown (like is the case now). You should be able to add the other states by altering the filter.

### LINKED ISSUE #386: HTML Report: Show additional mutant details
It would be useful if you could see the additional mutant details in the HTML report. 

Per mutant this information should be visible somehow:

* Which tests ran
* Mutator name
* Line/column location

Maybe in a table below, or a drawer panel at the left/right.

### PR DESCRIPTION
**Pull request by nicojs**
* Move to bootstrap 4 (from 3)
* Add a breadcrumb to all pages
* Add a popover tooltip for the selected mutants 
* Add mutant table on the file result page
* Add display checkboxes to filter different mutant states
* Update all ui tests and add some new ones.

Fixes #386, fixes #385, fixes #383

### CODE REVIEW

**Comment by joseluisgraa** [comment]
This would be really helpful. Will it be merged anytime soon?

**Comment by simondel** [comment]
Awesome job! The colors are a bit odd in the beginning but I think I'll get used to them. I love the `h1` font and all the awsome new features. 🥇

**Comment by simondel** [comment]
@joseluisgraa You can now use this if you upgrade to `stryker-html-reporter@0.9.0` 👍

**Comment by joseluisgraa** [comment]
Perfect! I'll give it a try tomorrow. Thanks!

2017-10-10 19:34 GMT+01:00 Simon de Lang <notifications@github.com>:

**Comment by nicojs** [comment]
> Awesome job!

Thanks a lot! 😁 

> The colors are a bit odd in the beginning but I think I'll get used to them

Yeah i know what you mean. They are really bright. Its the new bootstrap look, so i guess half the internet will look like our new html report soon. 😉

**Pull request merged**
