### PR TITLE
[WIP] maintenance: typings and eslint

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@nicojs while trying this one it appears that there might be a bug with newer version of jest ._. typings are just broken and I can't build it on my PC :/ 
```
packages/jest-runner/src/jestTestAdapters/JestLessThan25Adapter.ts:15:10 - error TS2416: Property 'run' in type 'JestLessThan25TestAdapter' is not assignable to the same property in base type 'JestTestAdapter'.
  Type '(jestConfig: Record<string, unknown>, projectRoot: string, fileNameUnderTest?: string | undefined) => Promise<{ results: AggregatedResult; globalConfig: GlobalConfig; }>' is not assignable to type '(config: Partial<{ automock: boolean; bail: number | boolean; cache: boolean; cacheDirectory: string; clearMocks: boolean; changedFilesWithAncestor: boolean; changedSince: string; collectCoverage: boolean; ... 91 more ...; watchPlugins: (string | [...])[]; }>, projectRoot: string, fileNameUnderTest?: 
string | undefi...'.
    Type 'Promise<{ results: AggregatedResult; globalConfig: GlobalConfig; }>' is not assignable to type 'Promise<JestRunResult>'.
      Type '{ results: AggregatedResult; globalConfig: GlobalConfig; }' is not assignable to type 'JestRunResult'.
        The types of 'globalConfig.coverageReporters' are incompatible between these types.
          Type 'import("C:/Users/groszek/Desktop/GitHub/stryker/packages/jest-runner/node_modules/jest-message-util/node_modules/@jest/types/build/Config").CoverageReporters' is not assignable to type 'import("C:/Users/groszek/Desktop/GitHub/stryker/packages/jest-runner/node_modules/@jest/types/build/Config").CoverageReporters'.
            Type '"json" | "clover" | "cobertura" | "html" | "json-summary" | "lcov" | "lcovonly" | "none" | "teamcity" | "text" | "text-lcov" | "text-summary" | "html-spa" | ["json", Partial<FileOptions>] | ... 10 more ... | [...]' is not assignable to 
type '"json" | "clover" | "cobertura" | "html" | "json-summary" | "lcov" | "lcovonly" | "none" | "teamcity" | "text" | "text-lcov" | "text-summary" | ["json", Partial<Options>] | ... 9 more ... | [...]'.
              Type '"html-spa"' is not assignable to type '"json" | "clover" | "cobertura" | "html" | "json-summary" | "lcov" | "lcovonly" | "none" | "teamcity" | "text" | "text-lcov" | "text-summary" | ["json", Partial<Options>] | ... 9 more ... | [...]'.
```

**Comment by nicojs** [comment]
> while trying this one it appears that there might be a bug with newer version of jest ._. typings are just broken and I can't build it on my PC 

It isn't broken for me or the build. Could you try this?

```
npx rimraf node_modules packages/*/node_modules
npm i
```

It might take a couple of minutes 😇

**Comment by kmdrGroch** [comment]
It indeed worked, probably some strange cache appeared since either changing versions nor npm prune didnt work :x

**Comment by nicojs** [comment]
Well, probably has to do with the fact that we're not using `package.lock.json` files. You're dependencies didn't have the same version as a clean installation had.

**Review by nicojs — APPROVED** [review]

**Comment by nicojs** [comment]
Can this be merged? It's still `[WIP]`?

**Comment by kmdrGroch** [comment]
I think it could be merged, tho I think I will look more tomorrow so depends on you :x

**Comment by nicojs** [comment]
I like smaller merge requests ;) Thanks again!

**Pull request merged**
