### PR TITLE
refactor: ESlint migration & prettier

### PR DESCRIPTION
**Pull request by kmdrGroch**
fixes: #1719
fixes: #1271

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Nico... I am soo sorry :< and you probably know why. But this prettier was so nicely configured by default and that `array-type` looks much better now >_<

**Comment by kmdrGroch** [comment]
travis... hello? I have removed TSlint -.-

**Comment by kmdrGroch** [comment]
@nicojs help... Travis hates me ;-;

**Comment by kmdrGroch** [comment]
IT'S GREEN *YAAAAAAAAS* 🎉

**Comment by kmdrGroch** [comment]
@nicojs If you could check & possibly merge this it would be nice <3 :3

**Comment by nicojs** [comment]
This looks really good! I'll have a closer look later today and if everything goes well I'll merge it. Thanks a lot! 👍

**Comment by nicojs** [comment]
I've added configure to fix-on-save in vscode. 

I absolutely love some of the rules eslint brings to the table. We enable more rules :). For example `@typescript-eslint/no-floating-promises`. There is no reason to have dangling promises, and they probably all bugs. Enabling the rule will show a couple of bugs. We can enable rules in separate issues IMHO, not in this one.

**Comment by kmdrGroch** [comment]
Love it @nicojs! For now it would be nice if you merge it. Then we can discuss other rules which should be changed! (Take a consideration that for now @typescript-eslint is ~beta version - it doesn't have all features it had before, and so some are missing like `ordered-imports` [unless they changed it in some last versions])

**Comment by nicojs** [comment]
Yeah, I've tried to enable ordered imports. It works, but it doesn't have the autofix feature: https://eslint.org/docs/rules/sort-imports

> The `--fix` option on the command line automatically fixes some problems reported by this rule: multiple members on a single line are automatically sorted (e.g. import { b, a } from 'foo.js' is corrected to import { a, b } from 'foo.js'), but multiple lines are not reordered.

Never mind that for now.  Thanks a lot once again. Logging off for tonight 🍻

**Pull request merged**
