### PR TITLE
Remove karma runner

### PR DESCRIPTION
**Pull request by nicojs**
* Move karma-runner from stryker repo to stryker-karma-runner
* Make the install-module integration test depend on that module
* Fix issues in PluginLoader:
	* Wrong plugin directory
	* Install only the basename of a module directory

### CODE REVIEW

**Comment by simondel** [comment]
It looks good! Can we also remove the sampleProject? It expects the Karma runner to be installed.

**Comment by nicojs** [comment]
Hmm true.. We can also add `stryker-karma-runner` as dev-dependency. That way we can still run the sample project. We can also add multiple sample projects per test runner and run them as integration test in the future.

@simondel  what do you think?

**Comment by simondel** [comment]
I think a dev-dependency is the way to go for now , nice suggestion :)

**Comment by nicojs** [comment]
The travis build is erroring, but i'll merge it as it does not seem to have to do with my changes

**Pull request merged**
