### PR TITLE
fix(ArrowFunction mutator): don't mutate () => undefined

### LINKED ISSUE #2306: ArrowFunction mutation question
**Question**

I don't get this mutation. Why did this fail?

```

[2020-07-09T21:03:12.538Z] 3. [Survived] ArrowFunction

[2020-07-09T21:03:12.538Z] /src/accordion/accordion-base.tsx:77:13

[2020-07-09T21:03:12.538Z] -       onClick: () => undefined,

[2020-07-09T21:03:12.538Z] +       onClick: () => undefined,
```

### PR DESCRIPTION
**Pull request by simondel**
Fixes #2306

### CODE REVIEW

**Comment by kmdrGroch** [comment]
It is so big if statement I would rather use normal "if/else" instead of ternary. It really reduces readability

**Comment by kmdrGroch** [comment]
And could you also check if "() => void" is mutated?

**Comment by brodybits** [comment]
> [...] ternary. It really reduces readability

I think there are 2 major causes:

- using extra-large `---print-width` setting in Prettier
- indenting issue that I just reported in <https://github.com/prettier/prettier/issues/8741>

This is really unfortunate, since I find ternaries to be much more too the point in general.

**Comment by rodoabad** [comment]
Yahoo! Thanks, @nicojs !

**Comment by nicojs** [comment]
Sure thing @rodoabad ! Just remember that this will be part of Stryker 4.0. I'm planning to release a new version of the beta later this week and we'll be working to a release this month or next month.

**Pull request merged**
