### PR TITLE
fix: update tree-kill to the latest version (#2278)

### PR DESCRIPTION
**Pull request by kmdrGroch**
fixes: #2278

### CODE REVIEW

**Comment by nicojs** [comment]
... Yeah. We want to merge this to master I think (instead of the mutation switch epic), because maintenance releases are still from master.

**Comment by kmdrGroch** [comment]
I also saw we again introduced ~ and ^ in versions... I think we should change them again to *one version* and leave it like that, since sometimes as could be seen in this example, package is not updated / installed properly... We would have better control over the versions (also it's time to update inside packages not only main package.json)

**Comment by nicojs** [comment]
I think dependabot is also taking care of updates within packages, no? But it won't make a merge request if the new release is within semver match of the current version. 

I think we should keep `~`, it should make sure we keep getting patch releases, right?

For kill-tree, could you make a new PR to master? This one has changes from the epic branch 🤷‍♂️

**Comment by kmdrGroch** [comment]
I think it doesn't check internal package.json files... At least I am not sure if it does. Doing PR now :)

**Pull request closed without merging**
