### PR TITLE
test(Webpack): use Webpack 4 in integration test

### LINKED ISSUE #630: Support webpack 4
Webpack release 4 contains a lot of breaking changes. 

https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

We should migrate the stryker-webpack-transpiler to support this version. It might make sense to not support 3 anymore (anyone interested in webpack 3 can still use the old version).

### PR DESCRIPTION
**Pull request by simondel**
Fixes #630 together with #664

### CODE REVIEW

**Comment by simondel** [comment]
Reading the `parents` property from a `chunk` is causing issues. I think this is the code: https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-webpack-transpiler/src/compiler/FileSorter.ts

**Comment by nicojs** [comment]
@simondel @Archcry 
Double check: we can remove the file chunk sorter right? Since we now leave file ordering up to test runners (transpilers are no longer responsible for file order)

**Comment by simondel** [comment]
From the webpack release notes:
> Chunk.chunks/parents/blocks are no longer Arrays. A Set is used internally and there are methods to access it.

This matches the error `Error: Chunk.parents: Use ChunkGroup.getParents() instead` that we get on Travis.

We should either try to remove the use of `chunk.parents` as @nicojs mentions or build a switch to see if we run on webpack 4 because then we have to use `ChunkGroup.getParents()`.

**Comment by Archcry** [comment]
I think we should remove the use of chunk.parents as @nicojs, the whole point in the refactoring we did in all the test-runners is partially because we do not want to rely on the ordering of the transpilers. So removing the sorting of chunks from the transpiler should resolve the problem.

**Comment by Archcry** [comment]
The issue is caused by `CommonsChunkPlugin` that is added to the Webpack configuration used while testing an Angular project. `CommonsChunkPlugin` has been removed from Webpack 4 but Angular still uses it. Therefore the integration tests are failing.

**Pull request merged**
