### PR TITLE
Remove dist folder

### PR DESCRIPTION
**Pull request by nicojs**
Because it is hard to reference files relative to source files we decided to remove the use of the dist folder

* Update grunt process
* Alter tsc config
* Moved all js and other resources needed for testing to testResources

### CODE REVIEW

**Comment by simondel** [comment]
It looks good, great job!
Could you change the **package.json** because it still references the `dist` folder in the `sample` script.

**Comment by nicojs** [comment]
Good catch! Why update grunt-stryker? Doesn't it just `require` stryker? That should still work. I was very happy with our integration test. It really helps to make sure the `require('stryker');` still works

**Comment by simondel** [comment]
Ah, you're right. I thought we couldn't simply `require('stryker')` but we can, so grunt-stryker doesn't have to be updated :)

Feel free to merge this PR.

**Comment by nicojs** [comment]
Thanks! :)

**Pull request merged**
