### PR TITLE
refactor: stricter tslint (#436)

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Things done:
- Refactor code a bit
- Style consistency (.ts, .spec.ts, .tsx files [there can be some other too, but i didnt focus on them])
- lint-info / lint-fix commands (tslint runs when you test everything but its like only tslint -> output in file)
Things that can be done
- eslint to lint js, spec.js, jsx files -> do same thing
Notes:
- You can ignore most of the issues like: empty objects etc (current "issues" are optional to be done - they are rather info for you [unless you can solve them])

**Comment by kmdrGroch** [comment]
@simondel, @nicojs could you please review it and tell what can be changed?

**Comment by kmdrGroch** [comment]
@nicojs warnings are caused by tslint, and they are rather just info for you, that "it would be good to don't do that". I can remove issues by "switching off" some tslint options or by hard fixing (although i dont know how to fix 1 thing)

**Comment by kmdrGroch** [comment]
@nicojs I have set default output to error so it won't even try to build if there is an tslint issue :)
I ask you, try fixing "unified-signatures" - set it to true and see these "issues" coz I really had no idea how to solve that (there are 2 places in 1 file with that issue)

**Comment by kmdrGroch** [comment]
Is any change still requested? :)

**Comment by kmdrGroch** [comment]
@nicojs and what about page PR? Anything to be changed there?

**Comment by nicojs** [comment]
Great and speedy fixes overall! I'm enabling and fixing `unified-signatures`, take one last look and, if everything is OK, merge it this evening.

**Comment by nicojs** [comment]
OK I just now realized that `npm run lint-fix` will automagically fix a lot of issues. Adding it to the CONTRIBUTING.md file.

**Comment by kmdrGroch** [comment]
@nicojs but you have to have in mind that ``npm run lint-fix`` can cause potential error (it is reaally rare, but I got 1 of issues like this - when you define same property in the function (sorry but i won't remember how to recreate it right now [still it is easy to solve - just remove repetition])

**Comment by nicojs** [comment]
>  You can also add to the documentation that npm run lint-info checks all files for tslint issues

Too late 😅 

Thanks for your effort so far. For the demo configs, please review my latest remark. Have fun! I'm interested in the demo configs you come up with.

**Pull request merged**
