### PR TITLE
feat(Initial test run): start timing the test run when logging that the run is starting

### LINKED ISSUE #2477: 4.0.0.Beta does not correctly report the initial test run time
The beta currently does not report the initial test run correctly. For example:

```
10:26:23 (3511) INFO DryRunExecutor Initial test run succeeded. Ran 59 tests in 30 seconds (net 21857 ms, overhead 34 ms).
```

The time here (30 seconds), is the total time until the initial test run completed. It would be better if we start the timer just before we start the test run, for example, when we `Starting initial test run. This may take a while.`

_Note: this is purely cosmetics. The timeout calculation is using the exact initial test run time_

### PR DESCRIPTION
**Pull request by simondel**
Fixes #2477

### CODE REVIEW

**Review by nicojs — CHANGES_REQUESTED** [review]
Great!!!

Add a test? 🤷‍♂️

**Review by nicojs — APPROVED** [review]

**Comment by simondel** [comment]
> 
> 
> Great!!!
> 
> Add a test? 🤷‍♂️

@nicojs How would you go about testing this?

**Review by nicojs — CHANGES_REQUESTED** [review]
We should not use the global timer here. You're working on a fix if I'm not mistaken.

**Comment by simondel** [comment]
> 
> 
> We should not use the global timer here. You're working on a fix if I'm not mistaken.

Yes, we still use the global timer, but we get the time based on the marker that was placed at the start of the test run. This marker was already used to report the `net` and `overhead` ms time.

**Review by nicojs — APPROVED** [review]
I've added a unit test for `Timer`

**Pull request merged**
