### PR TITLE
feat(striker-cli): add remark to run again with loglevel trace

### LINKED ISSUE #1205: Add remark to run again with loglevel trace
When Stryker crashes, it would be awesome if we could add a remark to run again with logLevel trace (when `fileLogLevel` wasn't already trace). Something like:

> Trouble figuring out what went wrong? Try `npx stryker run --fileLogLevel trace --logLevel debug` to get some more info.

Or something like that

### PR DESCRIPTION
**Pull request by bharaninb**
fixes #1205

### CODE REVIEW

**Comment by bharaninb** [comment]
Yeah sure. Will add tests as well.

**Comment by simondel** [comment]
If you need anything from me, feel free to let me know 👍

**Comment by bharaninb** [comment]
> If you need anything from me, feel free to let me know 👍

Sure, Thanks 👍

**Comment by simondel** [comment]
Thanks for fixing this!

**Pull request merged**
