### PR TITLE
update e2e dependencies

### PR DESCRIPTION
**Pull request by kmdrGroch**
fixes: #1697

### CODE REVIEW

**Comment by simondel** [comment]
Does the Angular E2E test work on your machine? The initial test run fails on the build server. This is a different error than the inconsistency error, so I think it is caused by your change. There is a possibility that it's caused by the Typescript upgrade in the Angular project. Angular is quite strict on which versions they allow.

**Comment by simondel** [comment]
Yes, I think Angular 8 only supports TypeScript 3.5.x

**Comment by simondel** [comment]
I find it so strange (and annoying) that the build doesn't trigger D:

**Comment by kmdrGroch** [comment]
I guess changing something which is working (travis) for something new, isnt always good -.-

**Comment by simondel** [comment]
21:59:39 (4055) ERROR InitialTestExecutor One or more tests resulted in an error:
	Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/runner/work/stryker/stryker/e2e/test/angular-project/.stryker-tmp/sandbox2803611/src

**Comment by kmdrGroch** [comment]
I'll close it and work independently on each dependency

**Pull request closed without merging**
