### PR TITLE
fix(Dependencies): Pin all deps on minor version

### LINKED ISSUE #967: tslib dependency is a few versions behind
### Summary

`tslib` is now at 1.9.3. Your versions are:
* `stryker`: ^1.5.0
* `stryker-api`: ^1.6.0
* `stryker-javascript-mutator`: ^1.8.0
* `stryker-karma-runner`: ^1.6.1
* `stryker-mocha-framework`: ^1.5.0
* `stryker-mocha-runner`: ^1.5.0
* `stryker-typescript`: ^1.5.0

 I'm particularly fond of [Greenkeeper](https://greenkeeper.io/) for CI and [npm-check-updates](https://github.com/tjunnone/npm-check-updates) for local development. Staying up-to-date on packages is generally a good idea:
* You get the latest bug fixes and improvements, particularly security patches
* You don't fall out of date with API needs (e.g. #566!)
* Users have fewer duplicate npm dependency versions resolved

### PR DESCRIPTION
**Pull request by nicojs**
This PR pins all _dependencies_ and _devDependencies_ on minor versions. I also consolidated all commonly used dependencies to most recent (supported) versions. Namely:

* log4js@~1.1.0 (we're upgrading to 2.x with #954)
* semver@~5.5.0
* tslib@~1.9.3

Fixes #967

### CODE REVIEW

**Comment by nicojs** [comment]
@simondel you can merge this if you're happy.

**Comment by nicojs** [comment]
There was a rather interesting loophole here by which we _still_ got @types for node@latest (even though we really want to make sure we support node 6, so pinned that version down). Fixed with [latest commit](https://github.com/stryker-mutator/stryker/pull/974/commits/e22cdea5ea9abdda327c9da2c1fcbcb4eea61eba).

**Comment by nicojs** [comment]
Some more shenanigans with the jest integration tests... @JoshuaKGoldberg you weren't kidding

> It's impossible to exactly follow semver, as even additions to an existing API can be breaking changes

**Comment by simondel** [comment]
Nice job!

**Pull request merged**
