### PR TITLE
fix(perf/angular-cli): upgrade to latest angular version and fix bugs

### PR DESCRIPTION
**Pull request by simondel**

### CODE REVIEW

**Comment by simondel** [comment]
Awesome, now we just have to revert the build change

**Comment by kmdrGroch** [comment]
Simon, could you btw please change all '^' into '~' in package.json?

**Comment by simondel** [comment]
Yeah, I will. The `ng update` command must have done that. Nice catch

**Comment by simondel** [comment]
@kmdrGroch Done!

**Comment by kmdrGroch** [comment]
Thanks @simondel ! But could you please rerun tests, since angular is not passing performance tests(?), It probably is false check but to be sure

**Pull request merged**
