### PR TITLE
Added colors to file names and line+col numbers in clear-text reporter

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Same cyan & yellow as TypeScript. It seems to work well there. Removes the extra lines of output as an opt-out behavior to make output more concise.

Starts on #975 _(fancy emojis can come next!)_

Before:

image

After:

image

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
I'm a little lost trying to get these unit tests to work with `chalk` 😕... if someone could help, I'd appreciate it!

**Comment by nicojs** [comment]
Hmm looks better I think. I'll have a look at the tests.

@simondel what do you think? It removes the names of the tests that ran, but do we really need them? It's a nice feature, but it also takes up a lot of space.

**Comment by JoshuaKGoldberg** [comment]
I also wonder if we really need the `Mutant survived!` complaint on top of each file. How about a `12/345 mutants survived!` once before the list?

**Comment by nicojs** [comment]
It is a lot of repeated text. It would be awesome if could at a remark in front of the mutator:

```
1. [Survived] StringLiteral
/tmp/cmp/success.component.js:5:5
-    controllerAs: 'cpt'
+    controllerAs: ''
2. [No coverage] BinaryOperator
/tmp/cmp/success.component.js:10:5
-    1+1
+    1-1
```

I would just remove the `Mutant survived!` entirely. I'm pretty sure it is remnant from the original code base, when @simondel was still a student :). A blast from the past.

**Comment by JoshuaKGoldberg** [comment]
If you don't mind, I think we could also remove the `Mutator: *Mutator` message too. Doesn't seem too useful to end users, and we can generally figure it out from the change. Removed in the latest commit.

**Comment by simondel** [comment]
RIP *Mutant Survived!*
2015 - 2018

**Comment by nicojs** [comment]
> If you don't mind, I think we could also remove the `Mutator: *Mutator` message too. 

This is actually useful info. If you want to disable a mutator, you need to know the name.

**Comment by nicojs** [comment]
I'm thinking of adding a global option for `allowColor`. Instead of one specific for the clear text reporter. Might be useful for the log4js formatting as well. @JoshuaKGoldberg is it OK if I move it to a separate issue?

**Comment by nicojs** [comment]
How about this?

image

**Comment by JoshuaKGoldberg** [comment]
> global option for `allowColor`

That sounds nice... though what if we want to have one reporter in color and another without? Would the `allowColor` set what the default is, as overridden by reporters?

I'll update this PR for the `105. [NoCoverage] Block`, and if your separate issue / branch is different and this PR gets closed, I won't be offended in the slightest. 😊

**Comment by nicojs** [comment]
@JoshuaKGoldberg I've created a separate issue for it. Could you explain it further there? #1218

**Pull request merged**
