### PR TITLE
Style fix and some #654 refactors

### PR DESCRIPTION
**Pull request by kmdrGroch**
I suppose i solved:
- [Rename 'project' config key to 'projectType'](#1076)
- [Rename 'timeoutMs' config key to 'timeoutMS'](#860)
- [Migrate to Lerna 3](#1080)
Although You should really take a close look on it since I am not 100% sure.

### CODE REVIEW

**Comment by simondel** [comment]
Thanks for making the changes!
I have a couple of remarks:
* Could you revert the Lerna change? Previous releases of the framework have caused quite a lot of trouble and since it's at the core of our release process, we want to prevent mistakes at any cost
* Feel free to ignore the mutators that are in the Stryker package directly from now on as we will completely delete the files once we go to v1.0.0. (that's what we mean by 'remove ES5 mutator)
* Our plan is to deprecate the configuration changes that you made instead of completely removing the old functionality. For example, if someone has "timeoutMs" in their config, they should get a warning telling them to stop using "timeoutMs" and start using "timeoutMS". Stryker should still be able to run without a problem. This makes it easy for users to upgrade to the new version. With 1.0.0 we will remove the support for the old property, forcing people to update the config if they haven't already. For 1.0.0 we will have a guide with all the changes you have to make to upgrade.

**Comment by kmdrGroch** [comment]
I can surely revert Lerna change. Honestly i dunno how to implement these ``deprecation`` warnings at this moment, so now these options are just replaced

**Comment by kmdrGroch** [comment]
@simondel, we could try that way. Also reverting Lerna change right now

**Comment by simondel** [comment]
Awesome :) if you make a new branch with just the karma change and then create a new pull request for it, I'll add the test tomorrow!

**Comment by kmdrGroch** [comment]
@simondel and what if in ``styker/.../ConfigReader`` in ``readConfig`` function add
```js
if (config.timeoutMs) {
      config.timeoutMS = config.timeoutMs;
      console.warn('[Deprecation warning] use timeoutMS instead of timeoutMs');
    }
    if (config.project) {
      config.projectType = config.project;
      console.warn('[Deprecation warning] use projectType instead of project');
    }
```

**Comment by kmdrGroch** [comment]
@simondel you can look how i kinda make it work -> test passes, although now it is just throwing an error (since i didn't know how to test warning message) [this commit is to undo although you can see my vision / method of doing this]

**Comment by simondel** [comment]
@kmdrGroch I have an example of deprecating a property in #1088

**Comment by kmdrGroch** [comment]
I'll be able to take a deeper look when I come back home, so after a week. But it looks nice and replicable.

**Pull request closed without merging**
