### PR TITLE
build: Update angular test project

### PR DESCRIPTION
**Pull request by Archcry**
Update the Angular project in the integration tests folder in an attempt to get rid of the dependency warnings on github.

### CODE REVIEW

**Comment by simondel** [comment]
Did you just do another `ng new`?

**Comment by Archcry** [comment]
Jep

**Comment by simondel** [comment]
I updated the title from **chore** to **build** because we moved from AngularJS to Angular commit messages: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

(I think we still have to change this in the contributing.md)

**Comment by Archcry** [comment]
> (I think we still have to change this in the contributing.md)

Ye we should.

**Comment by nicojs** [comment]
Looks good. When the build is green we can merge.

**Pull request merged**
