### PR TITLE
ci: increase timeout for the perf test to 20 minutes

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR should increase the maximum timeout to 20 minutes.

### CODE REVIEW

**Comment by nicojs** [comment]
Awesome! Didn't know this was possible. I'll merge it in when green.

**Comment by DanielRuf** [comment]
I've temporarily enabled the performance test to see the actual result.

See https://docs.travis-ci.com/user/common-build-problems/#my-builds-are-timing-out for common solutions.

**Comment by DanielRuf** [comment]
Yep, like I've expected it. Let's see if the other recommended solution works using a background process.

Reference: https://github.com/travis-ci/dpl/issues/568#issuecomment-272465349

**Comment by DanielRuf** [comment]
I'll inspect execa and the underlying spawned child process. There is probably another part which has a timeout.

**Comment by nicojs** [comment]
Hi @DanielRuf I see you've deleted the branch. Does that mean you've given up on this? 😢

What was the problem you ran into?

**Comment by DanielRuf** [comment]
It's fixed by removing the execa timeout (my other PR which is already merged).

**Comment by nicojs** [comment]
Ah yes, realized that later. Thanks for figuring out what's wrong!

**Pull request closed without merging**
