### PR TITLE
chore(ts 2.6): Support TypeScript 2.6

### PR DESCRIPTION
**Pull request by nicojs**
* Remove unused variables
* Alter types for co- and contra variance

### CODE REVIEW

**Comment by simondel** [comment]
Awesome! Why did you have to specify the datatype in the HTML reporter but not in the function above? Vscode seems to know that type implicitly

**Comment by nicojs** [comment]
> Why did you have to specify the datatype in the HTML reporter but not in the function above?

Do you mean this method?

```typescript
  async rows() {
    const rows: ElementFinder[] = await this.host.$$('tbody tr');
    return rows.map(row => new ResultTableRow(row));
  }
```

The reason that `rows` need to be typed explicitly is the return type of `await this.host.$$('tbody tr');` is of type `any[] | ElementFinder[]`. Maybe the typings could have been defined better, but being what they are now they provide a compiler error because of the awesome addition of `--strictFunctions` (enabled by default, because we're running in `--strict` mode).

**Comment by simondel** [comment]
I was talking about this line:
```ts
  head() {
    return this.host.$$('thead th');
  }
```

**Comment by nicojs** [comment]
> Does that not cause issues because we don't await it?

Why should it? It's not used anywhere  :sweat_smile:

**Pull request merged**
