### PR TITLE
Add source type: module

### PR DESCRIPTION
**Pull request by jeznag**

### CODE REVIEW

**Comment by simondel** [comment]
What would this fix for you? Also, we're moving to LernaJS so merging this will be a bit delayed.

**Comment by SxMShaDoW** [comment]
One of my projects is also using `es6 modules`. Are we able to figure how to support es6 modules without extra configuration?

**Comment by simondel** [comment]
Full ES6 support is a bit of an issue unfortunately. The module we use to genrage code is no longer supported and the module that I want to use instead isn't documented well enough to easily implement it

**Comment by jeznag** [comment]
@simondel it seems to work fine for me with ES6 code as long as I either use babel-node or Node v7 + sourceType: module. What are the other ES6 issues that need to be resolved?

**Comment by SxMShaDoW** [comment]
Hmm. I tried to clone your fork and npm link it without any luck. Am I missing something @jeznag ? Id love to use it with node 7. My hypothesis is supporting babel / node 7 would get a lot more visibility in the community.

**Comment by jeznag** [comment]
@SxMShaDoW what errors do you get using it with NodeV7? It works fine for me. To handle import statements, I've had to change the stryker exec to have `#!/usr/bin/env babel-node`

**Comment by SxMShaDoW** [comment]
@jeznag - I got similar error to the travis ci job

``` Running "ts:build" (ts) task
Compiling...
Using tsc v2.2.1
src/utils/parserUtils.ts(29,50): error TS2345: Argument of type '{ comment: boolean; loc: boolean; sourceType: string; range: boolean; tokens: boolean; }' is not assignable to parameter of type 'Options | undefined'.
  Type '{ comment: boolean; loc: boolean; sourceType: string; range: boolean; tokens: boolean; }' is not assignable to type 'Options'.
    Types of property 'sourceType' are incompatible.
      Type 'string' is not assignable to type '"script" | "module" | undefined'. 
```

thus I wasn't able to npm link it.

As far as the changes to stryker exec for imports, you should include the file change as well if people wan tot handle imports :). Still hoping a solution will exist in the future. 

Would love to see this work with [create-react-app](https://github.com/facebookincubator/create-react-app) out of the box.

**Comment by simondel** [comment]
We won't fix this for now. We will fix it when supporting es6. See also https://github.com/stryker-mutator/stryker/issues/101

**Pull request closed without merging**
