### PR TITLE
maintenance(lint): adher to new linting rules

### PR DESCRIPTION
**Pull request by nicojs**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@nicojs I guess prettier won't allow you to make it in one line since our limit is 150letters per row(?)

**Comment by nicojs** [comment]
Yes, strange how the rules suddenly got stricter. I guess bugfixing in their part, and since we're not locking our versions, we get the latest and greatest each time.

Run this locally to reproduce:: `rm -rf node_modules packages/*/node_modules && npm i`

**Comment by nicojs** [comment]
Whut???? No file changes? 😲

**Comment by nicojs** [comment]
Abandon 🙈

**Comment by kmdrGroch** [comment]
yea nico, there were some strange caches in package.json file. I had to reinstall whole stryker coz i had some problems with doubling references. *happens*

**Pull request closed without merging**
