### PR TITLE
core/readme: Reordering Config Section

### PR DESCRIPTION
**Pull request by gugacavalieri**
# Changelog:
* reordering Config Section
* adding an index to config section

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Uhh that looks pretty to me :3

**Comment by gugacavalieri** [comment]
@kmdrGroch Good suggestion !!

I still have to figure out why the anchor links are not working. 

Gonna mark this as **DON'T MERGE YET**

**Comment by kmdrGroch** [comment]
Still first of all someone from Stryker team has to accept it :< a I'm only unofficial maintainer

**Comment by gugacavalieri** [comment]
Just fixed the anchors and added @kmdrGroch suggestion :)

**Comment by gugacavalieri** [comment]
retest this please

**Comment by simondel** [comment]
Thanks! <3

**Pull request merged**
