### PR TITLE
Added support for yarn installs to `stryker init`

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Starts on #917.

### CODE REVIEW

**Comment by nicojs** [comment]
Hi @JoshuaKGoldberg , you're off to an awesome start! I took the liberty of fixing the compile errors. I used inquires generic type argument for that (and refactored it in the other calls). We might be able to fix this issue in inquirer's typings using mapped types. Would be an awesome use case for it.

I also fixed one unit test. I saw there were some other ones failing, you want me to fix those as well? 

Thanks a lot for all the work already!

**Comment by JoshuaKGoldberg** [comment]
Ha, thanks - I was planning on re-checking this tonight. I can do them!

**Comment by JoshuaKGoldberg** [comment]
I hope you'll forgive spacing some of the test object literals across lines; I found it hard to read having several members on the same line. Otherwise, unit tests are fixed. They caught that I was neglecting to write the selected package manager to the config file! 🚀

**Comment by nicojs** [comment]
> I hope you'll forgive spacing some of the test object literals across lines; I

No problem! I'm still planning of integrating something like [prettier](https://www.npmjs.com/package/prettier) in our build pipeline, but haven't got around to it.

> They caught that I was neglecting to write the selected package manager to the config file! rocket

Well.. that might be an oversight on our part. Do we want the packageManager config setting? I suppose it won't hurt and we could use it in the future I guess. What do you think?

If I had to write the tests again today, i would introduce a helper method to arrange the test cases. Making them a bit more DRY. I seem to go back and forth on the dry vs damp discussion

**Comment by JoshuaKGoldberg** [comment]
I would prefer to leave it in precisely for the future proofing, yes. Seems harmless otherwise?

**Comment by nicojs** [comment]
@JoshuaKGoldberg awesome, thanks for your work 🐍

**Comment by simondel** [comment]
Amazing 🏅

**Pull request merged**
