### PR TITLE
[WIP] Fix jest types / exports problems

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
@nicojs I need your help. Somehow I manage to run everything on my PC and it works but here it doesn't :/ strange

**Comment by simondel** [comment]
Thanks for giving this a shot! How will this work with Jest 24?

**Comment by simondel** [comment]
Regarding the build failure, it looks like the `runCLI` stub isn't called properly, causing Jest to actually run:
```
@stryker-mutator/jest-runner: No tests found, exiting with code 1
@stryker-mutator/jest-runner: Run with `--passWithNoTests` to exit with code 0
@stryker-mutator/jest-runner: No files found in /path/to/project.
@stryker-mutator/jest-runner: Make sure Jest's configuration does not exclude this directory.
@stryker-mutator/jest-runner: To set up Jest, make sure a package.json file exists.
@stryker-mutator/jest-runner: Jest Documentation: facebook.github.io/jest/docs/configuration.html
@stryker-mutator/jest-runner: Pattern:  - 0 matches
@stryker-mutator/jest-runner: ERROR: Coverage for lines (67.16%) does not meet global threshold (80%)
@stryker-mutator/jest-runner: ERROR: Coverage for functions (62.5%) does not meet global threshold (80%)
@stryker-mutator/jest-runner: ERROR: Coverage for branches (42.31%) does not meet global threshold (75%)
@stryker-mutator/jest-runner: npm ERR! code ELIFECYCLE
```

**Comment by kmdrGroch** [comment]
It's strange @simondel, as I said, it works on my PC :/ And typescript says this method exists. I have to check with @types/jest i guess. about 24 support. I will make both work, so don't worry

**Comment by kmdrGroch** [comment]
@simondel I am going to check if `jest` is actually updated to v25. If it is, it might be an issue with runCLI function tho, since I have console.log both version 24 and 25 and both of them contain runCLI :/

**Comment by kmdrGroch** [comment]
@simondel it seems jest is correctly updated to the newest version, but somehow stub doesn't work(?).

**Comment by nicojs** [comment]
I'm busy with fixing this in #1979

**Pull request closed without merging**
