### PR TITLE
Update tsconfig.json

### LINKED ISSUE #1206: Enable `strictFunctionTypes` tsconfig option
Enable `strictFunctionTypes` tsconfig option (in the root tsconfig.json file) and fix any build errors that come along.

### PR DESCRIPTION
**Pull request by josecolella**
Add strictFunctionTypes. Fixes #1206

### CODE REVIEW

**Comment by simondel** [comment]
Thanks for opening this issue! It looks like the code doesn't compile yet. Could you take a look at that?

**Comment by kmdrGroch** [comment]
@simondel 
```
src/index.ts(4,45): error TS2345: Argument of type 'typeof HtmlReporter' is not assignable to parameter of type 'new (settings: StrykerOptions) => Reporter'.
  Types of parameters 'options' and 'settings' are incompatible.
    Type 'StrykerOptions' is not assignable to type 'Config'.
      Property 'set' is missing in type 'StrykerOptions'.
src/templates/sourceFile.tsx(140,78): error TS2345: Argument of type '(char: string, index: number) => string | undefined' is not assignable to parameter of type '(char: string, index?: number | undefined) => string | undefined'.
  Types of parameters 'index' and 'index' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.```
some types problem :/
@nicojs maybe this is quite a good example for my previous issue about "let's type everything"

**Comment by nicojs** [comment]
Couldn't this be easily fixed if we change the type of the HtmlReporter from `StrykerOptions` to `Config`? Later we will remove the `Config` class entirely. But for now, it would be a good short term solution. @josecolella Could you give it a try?

**Comment by josecolella** [comment]
@nicojs Yes. Let me give it a try

**Comment by kmdrGroch** [comment]
@josecolella if sth, I have covered this in <https://github.com/stryker-mutator/stryker/pull/1219/files>. You can check what / where was changed so it will be easier for you to debug

**Comment by nicojs** [comment]
@josecolella You still on the ball for this one?

**Comment by josecolella** [comment]
Yup.

**Comment by kmdrGroch** [comment]
As i said @josecolella just check out my PR if you stuck :/

**Comment by josecolella** [comment]
@kmdrGroch Thanks for your help. I added all the changes, and there are no more tslint issues.

**Comment by nicojs** [comment]
@josecolella thanks for the fix.

Do you have experience with prettier? I've been wanting to add some kind of prettier support for a while now. Do you have suggestions on how to add it? If so, would you mind opening an issue and writing down some suggestions? Any help on this topic will be very much appreciated!

**Comment by josecolella** [comment]
@nicojs I do have experience with prettier. I use prettier on a day to day basis. I can create an issue and create a PR, for it. Do you have have preferences on single vs double quotes and width?

**Pull request merged**
