### PR TITLE
WIP: Add mocha runner

### PR DESCRIPTION
**Pull request by simondel**
This is still a WIP. Don't merge it.

### CODE REVIEW

**Comment by nicojs** [comment]
We should `import` this package instead: https://github.com/lerna/lerna/#import

**Comment by simondel** [comment]
Does that mean you also don't want to squash merge?

**Comment by nicojs** [comment]
Haha yes squashing would be counter productive

**Comment by simondel** [comment]
So shall I `import` -> merge regularly -> make it pretty -> squash merge?

**Comment by nicojs** [comment]
Hmm yeah, good idea. How about:

```
Branch
    Import
          Branch
          Fix stuff
     Squash
Regular merge
```

**Comment by simondel** [comment]
Sounds good!

**Pull request closed without merging**
